name: Helm Testing chart
description: Testing a archive from given Chart
author: nolte
inputs:
  path:
    description: Relative path under $GITHUB_WORKSPACE to run the linter against
    default: ... 
    required: false
runs:
  using: docker
  image: docker://quay.io/helmpack/chart-testing
  entrypoint: ct
  args:
  - "lint"
  - "--all"
  - "--chart-dirs"
  - "/github"
branding:
  icon: alert-circle
  color: blue