---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)(
                .md|
                .bumpversion.cfg
            )
      - id: end-of-file-fixer
        exclude: ".bumpversion.cfg"
      - id: check-yaml
        exclude: "maintenance/*"
  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.20.0
    hooks:
      - id: yamllint
